language: ruby
rvm:
  - 2.7.0
install:
  - bundle install
  - nvm install 14
  - npm i -g yarn
  - yarn
services:
  - postgresql
script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - bundle exec rspec
cache:
  - bundler
  - nvm
  - yarn
